### PR TITLE
Specify a username and icon for webhook

### PR DESCRIPTION
**Pull request by jeffgdotorg**
User can set through environment variable; default to "JIRA" and the
Atlassian favicon. Note MM must be configured to allow setting these
items.

### CODE REVIEW

**Comment by jeffgdotorg** [comment]
Looks like this:
screenshot from 2016-03-20 13-58-31

**Comment by vrenjith** [comment]
Jeff, you have tested this, right?

**Comment by jeffgdotorg** [comment]
Yes, tested rather thoroughly against a MatterMost 2.1 installation.

**Comment by jeffgdotorg** [comment]
Example of configuring both items via environment:

MATTERMOST_USERNAME="OpenNMS JIRA"
MATTERMOST_ICON_URL=https://3.bp.blogspot.com/-XW53x5pJqCw/U1OwAZ621nI/AAAAAAAAEsQ/wTbP_d-KzeY/s1600/Meeko_Diving.jpg

**Pull request merged**
